### ISSUE TITLE
Prepare milestone 3 release

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/aragon#29]
- [x] update readme with step by step commands to install the app on a DAO
- [x] add useful commands for other developers (list version, publish, etc...)
- [x] create new demo video that shows the new UI
  - show quickly all the available tasks (select each of them to show the inputs)
  - create a telegram connection
  - trigger the connection
- [x] add/update description to README of what the app can do (list services/tasks) and what needs to be done (add deletion of connections)
- [x] remove aragon app description and screenshots https://github.com/mesg-foundation/aragon/blob/master/app/public/meta/
- [x] publish it on aragon rinkeby, make sure to update the commands if needed
